server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
